---
title: "US East Coast Oyster Nutrient Removal Calculator"
output: pdf_document
date: "`r format(Sys.Date(),'%B %e, %Y')`"
params: 
  n: NA
  table: 'NULL'
  plot: 'NULL'
  Farm: NA
  Location: NA
  Tissue.N: NA
  Shell.N: NA
  Tissue.P: NA 
  Shell.P: NA 
  Total.N: NA  
  Total.P: NA
  Units: NA 
  gear: NA 
  ploidy: NA  
  hsize: NA  
  Number: NA
  htime: NA 
  loc2: NA
  Lat: NA
  Lon: NA
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F)
```


```{r, include=FALSE}
options(tinytex.verbose = TRUE)
```


```{r, echo=FALSE,warning=FALSE}
print(paste("Name of the oyster farm: ", params[["Farm"]]))
print(paste("Name of the water body where the oyster farm is located: ", params[["Location"]]))
print(paste("Gear used for growing oysters: ", params[["gear"]]))
print(paste("Oyster ploidy: ", params[["ploidy"]]))
print(paste("Average oyster size at harvest (Inches): " ,params[["hsize"]]))
print(paste("Number of oysters harvested: ", params[["Number"]]))
print(paste("Units for nutrient removal: ", params[["Units"]]))

```


```{r}
print(paste("Farm location: " , c(params[["Lon"]]),params[["Lat"]]))
```

```{r}
print("Estimated Farm Mediated Nitrogen Removal")
params[["table"]]
```

```{r}
params[["plot"]]
```